name: Auto Merge Pull Requests Checks
on:
  pull_request:
    branches:
      - master
  pull_request_target:
    branches:
      - master

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build Web Application
        run: ./gradlew :composeApp:wasmBrowserDevelopmentExecutableDistribution

      - name: Build Desktop Application
        run: ./gradlew :composeApp:packageDistributionForCurrentOS

      - name: Automatically Merge Dependabot PRs
        if: success()
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: "dependencies"
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_FILTER_AUTHOR: "dependabot[bot]"